export interface SeedVocabulary {
  ghegWord: string;
  englishMeaning: string;
  partOfSpeech: string;
  exampleSentence: string;
  introducedWeek: number;
  frequency: string; // "high", "medium", "low"
}

export const vocabulary: SeedVocabulary[] = [
  // ─── Week 1: Core Verbs ───────────────────────────────────────────────────
  {
    ghegWord: "jeton",
    englishMeaning: "lives / to live",
    partOfSpeech: "verb",
    exampleSentence: "Ai jeton në Prishtinë.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "punon",
    englishMeaning: "works / to work",
    partOfSpeech: "verb",
    exampleSentence: "Ajo punon çdo ditë.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "ha",
    englishMeaning: "eats / to eat",
    partOfSpeech: "verb",
    exampleSentence: "Unë ha bukë në mëngjes.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "pi",
    englishMeaning: "drinks / to drink",
    partOfSpeech: "verb",
    exampleSentence: "Ti pi ujë apo kafe?",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "shkon",
    englishMeaning: "goes / to go",
    partOfSpeech: "verb",
    exampleSentence: "Ai shkon në punë me autobus.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "vjen",
    englishMeaning: "comes / to come",
    partOfSpeech: "verb",
    exampleSentence: "Ajo vjen shtëpi vonë.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "flet",
    englishMeaning: "speaks / to speak",
    partOfSpeech: "verb",
    exampleSentence: "Ai flet shqip shumë mirë.",
    introducedWeek: 1,
    frequency: "high",
  },
  // ─── Week 1: Pronouns ─────────────────────────────────────────────────────
  {
    ghegWord: "unë",
    englishMeaning: "I / me",
    partOfSpeech: "pronoun",
    exampleSentence: "Unë jam prej Kosovës.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "ti",
    englishMeaning: "you (singular)",
    partOfSpeech: "pronoun",
    exampleSentence: "Ti flet shqip?",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "ai",
    englishMeaning: "he",
    partOfSpeech: "pronoun",
    exampleSentence: "Ai asht miku im.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "ajo",
    englishMeaning: "she",
    partOfSpeech: "pronoun",
    exampleSentence: "Ajo asht mësuese.",
    introducedWeek: 1,
    frequency: "high",
  },
  // ─── Week 1: Greetings ────────────────────────────────────────────────────
  {
    ghegWord: "tungjatjeta",
    englishMeaning: "hello / greetings",
    partOfSpeech: "interjection",
    exampleSentence: "Tungjatjeta, si jeni?",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "mirëdita",
    englishMeaning: "good day / good afternoon",
    partOfSpeech: "interjection",
    exampleSentence: "Mirëdita, çfarë bani sot?",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "mirëmëngjes",
    englishMeaning: "good morning",
    partOfSpeech: "interjection",
    exampleSentence: "Mirëmëngjes, si kalove natën?",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "natën e mirë",
    englishMeaning: "good night",
    partOfSpeech: "interjection",
    exampleSentence: "Natën e mirë, fle mirë!",
    introducedWeek: 1,
    frequency: "high",
  },
  // ─── Week 1: Family (core) ────────────────────────────────────────────────
  {
    ghegWord: "nënë",
    englishMeaning: "mother / mom",
    partOfSpeech: "noun",
    exampleSentence: "Nënë ime gatuen çdo ditë.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "babë",
    englishMeaning: "father / dad",
    partOfSpeech: "noun",
    exampleSentence: "Babë im punon në qytet.",
    introducedWeek: 1,
    frequency: "high",
  },
  // ─── Week 1: Places ───────────────────────────────────────────────────────
  {
    ghegWord: "shtëpi",
    englishMeaning: "house / home",
    partOfSpeech: "noun",
    exampleSentence: "Shtëpia jonë asht e madhe.",
    introducedWeek: 1,
    frequency: "high",
  },
  {
    ghegWord: "qytet",
    englishMeaning: "city / town",
    partOfSpeech: "noun",
    exampleSentence: "Prishtina asht qyteti kryesor i Kosovës.",
    introducedWeek: 1,
    frequency: "high",
  },
  // ─── Week 2: Family (extended) ────────────────────────────────────────────
  {
    ghegWord: "vëlla",
    englishMeaning: "brother",
    partOfSpeech: "noun",
    exampleSentence: "Vëlla im asht i ri.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "motër",
    englishMeaning: "sister",
    partOfSpeech: "noun",
    exampleSentence: "Motra ime studion në universitet.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "gjysh",
    englishMeaning: "grandfather",
    partOfSpeech: "noun",
    exampleSentence: "Gjyshi im tregon histori të vjetra.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "gjyshe",
    englishMeaning: "grandmother",
    partOfSpeech: "noun",
    exampleSentence: "Gjyshja gatuen byrek të mirë.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "daj",
    englishMeaning: "uncle (maternal)",
    partOfSpeech: "noun",
    exampleSentence: "Daja im banon në Gjermani.",
    introducedWeek: 2,
    frequency: "medium",
  },
  {
    ghegWord: "hallë",
    englishMeaning: "aunt (paternal)",
    partOfSpeech: "noun",
    exampleSentence: "Halla ime asht mësuese.",
    introducedWeek: 2,
    frequency: "medium",
  },
  // ─── Week 2: House / Rooms ────────────────────────────────────────────────
  {
    ghegWord: "dhomë",
    englishMeaning: "room",
    partOfSpeech: "noun",
    exampleSentence: "Dhoma ime asht në katin e dytë.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "kuzhinë",
    englishMeaning: "kitchen",
    partOfSpeech: "noun",
    exampleSentence: "Nëna gatuen në kuzhinë.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "oborr",
    englishMeaning: "yard / courtyard",
    partOfSpeech: "noun",
    exampleSentence: "Fëmijët luajnë në oborr.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "derë",
    englishMeaning: "door",
    partOfSpeech: "noun",
    exampleSentence: "Dere asht e hapur.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "dritare",
    englishMeaning: "window",
    partOfSpeech: "noun",
    exampleSentence: "Hap dritaren, asht nxehtë.",
    introducedWeek: 2,
    frequency: "medium",
  },
  // ─── Week 2: Adjectives ───────────────────────────────────────────────────
  {
    ghegWord: "i madh",
    englishMeaning: "big / large (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Ky qytet asht i madh.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "i vogël",
    englishMeaning: "small / little (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Fëmija asht i vogël.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "i bukur",
    englishMeaning: "beautiful / handsome (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Kjo fustanë asht e bukur.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "i mirë",
    englishMeaning: "good / kind (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Ai asht njeri i mirë.",
    introducedWeek: 2,
    frequency: "high",
  },
  {
    ghegWord: "i ri",
    englishMeaning: "young / new (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Vëllai im asht i ri.",
    introducedWeek: 2,
    frequency: "high",
  },
  // ─── Week 3: Food ─────────────────────────────────────────────────────────
  {
    ghegWord: "bukë",
    englishMeaning: "bread",
    partOfSpeech: "noun",
    exampleSentence: "Ha bukë me djathë çdo mëngjes.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "djathë",
    englishMeaning: "cheese",
    partOfSpeech: "noun",
    exampleSentence: "Djathi kosovar asht shumë i mirë.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "qumësht",
    englishMeaning: "milk",
    partOfSpeech: "noun",
    exampleSentence: "Fëmija pi qumësht çdo natë.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "fruta",
    englishMeaning: "fruit",
    partOfSpeech: "noun",
    exampleSentence: "Bleva fruta të freskëta nga tregu.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "perime",
    englishMeaning: "vegetables",
    partOfSpeech: "noun",
    exampleSentence: "Nëna blen perime çdo ditë.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "mish",
    englishMeaning: "meat",
    partOfSpeech: "noun",
    exampleSentence: "Babë grillon mish të shtunave.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "ujë",
    englishMeaning: "water",
    partOfSpeech: "noun",
    exampleSentence: "Pi ujë, jo pije me sheqer.",
    introducedWeek: 3,
    frequency: "high",
  },
  // ─── Week 3: Numbers ──────────────────────────────────────────────────────
  {
    ghegWord: "një",
    englishMeaning: "one",
    partOfSpeech: "numeral",
    exampleSentence: "Kam një vëlla.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "dy",
    englishMeaning: "two",
    partOfSpeech: "numeral",
    exampleSentence: "Kemi dy dhoma gjumi.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "tri",
    englishMeaning: "three",
    partOfSpeech: "numeral",
    exampleSentence: "Bleva tri mollë nga tregu.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "katër",
    englishMeaning: "four",
    partOfSpeech: "numeral",
    exampleSentence: "Familja jonë ka katër anëtarë.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "pesë",
    englishMeaning: "five",
    partOfSpeech: "numeral",
    exampleSentence: "Ai punon pesë ditë në javë.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "gjashtë",
    englishMeaning: "six",
    partOfSpeech: "numeral",
    exampleSentence: "Shkolla fillon në orën gjashtë e gjysmë.",
    introducedWeek: 3,
    frequency: "medium",
  },
  {
    ghegWord: "shtatë",
    englishMeaning: "seven",
    partOfSpeech: "numeral",
    exampleSentence: "Ka shtatë ditë në javë.",
    introducedWeek: 3,
    frequency: "medium",
  },
  {
    ghegWord: "tetë",
    englishMeaning: "eight",
    partOfSpeech: "numeral",
    exampleSentence: "Autobusi vjen në orën tetë.",
    introducedWeek: 3,
    frequency: "medium",
  },
  {
    ghegWord: "nëntë",
    englishMeaning: "nine",
    partOfSpeech: "numeral",
    exampleSentence: "Mësimi fillon në orën nëntë.",
    introducedWeek: 3,
    frequency: "medium",
  },
  {
    ghegWord: "dhjetë",
    englishMeaning: "ten",
    partOfSpeech: "numeral",
    exampleSentence: "Bleva dhjetë vezë nga tregu.",
    introducedWeek: 3,
    frequency: "medium",
  },
  // ─── Week 3: Market vocabulary ────────────────────────────────────────────
  {
    ghegWord: "treg",
    englishMeaning: "market / bazaar",
    partOfSpeech: "noun",
    exampleSentence: "Shkojmë në treg çdo të shtunë.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "blej",
    englishMeaning: "I buy / to buy",
    partOfSpeech: "verb",
    exampleSentence: "Blej bukë dhe djathë nga dyqani.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "shes",
    englishMeaning: "I sell / to sell",
    partOfSpeech: "verb",
    exampleSentence: "Ai shet perime në treg.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "para",
    englishMeaning: "money",
    partOfSpeech: "noun",
    exampleSentence: "Sa para kushton kjo?",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "çmim",
    englishMeaning: "price",
    partOfSpeech: "noun",
    exampleSentence: "Çmimi i frutave asht i lirë sot.",
    introducedWeek: 3,
    frequency: "high",
  },
  {
    ghegWord: "i lirë",
    englishMeaning: "cheap / free (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Ky produkt asht i lirë.",
    introducedWeek: 3,
    frequency: "medium",
  },
  {
    ghegWord: "i shtrenjtë",
    englishMeaning: "expensive (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Mishi asht i shtrenjtë këtë javë.",
    introducedWeek: 3,
    frequency: "medium",
  },
  // ─── Week 4: School ───────────────────────────────────────────────────────
  {
    ghegWord: "shkollë",
    englishMeaning: "school",
    partOfSpeech: "noun",
    exampleSentence: "Fëmija shkon në shkollë çdo ditë.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "mësuese",
    englishMeaning: "teacher (female)",
    partOfSpeech: "noun",
    exampleSentence: "Mësuesia jonë asht shumë e mirë.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "mësues",
    englishMeaning: "teacher (male)",
    partOfSpeech: "noun",
    exampleSentence: "Mësuesi shpjegon mësimet qartë.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "nxënës",
    englishMeaning: "student / pupil",
    partOfSpeech: "noun",
    exampleSentence: "Nxënësit dëgjojnë mësuesen me vëmendje.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "libër",
    englishMeaning: "book",
    partOfSpeech: "noun",
    exampleSentence: "Libri i matematikës asht i rëndë.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "klasë",
    englishMeaning: "classroom / class",
    partOfSpeech: "noun",
    exampleSentence: "Klasa jonë ka njëzet nxënës.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "matematikë",
    englishMeaning: "mathematics",
    partOfSpeech: "noun",
    exampleSentence: "Matematika asht lënda ime e preferuar.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "gjuhë",
    englishMeaning: "language / tongue",
    partOfSpeech: "noun",
    exampleSentence: "Mëson gjuhën shqipe me kënaqësi.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "detyra",
    englishMeaning: "homework / task",
    partOfSpeech: "noun",
    exampleSentence: "Bëj detyrat para darkës.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "shkruej",
    englishMeaning: "I write / to write",
    partOfSpeech: "verb",
    exampleSentence: "Shkruej detyrat me laps.",
    introducedWeek: 4,
    frequency: "high",
  },
  // ─── Week 4: Time of day ──────────────────────────────────────────────────
  {
    ghegWord: "mëngjes",
    englishMeaning: "morning",
    partOfSpeech: "noun",
    exampleSentence: "Çohem herët çdo mëngjes.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "drekë",
    englishMeaning: "lunch / noon",
    partOfSpeech: "noun",
    exampleSentence: "Hamë drekë bashkë si familje.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "mbrëmje",
    englishMeaning: "evening",
    partOfSpeech: "noun",
    exampleSentence: "Në mbrëmje shohim televizor.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "sot",
    englishMeaning: "today",
    partOfSpeech: "adverb",
    exampleSentence: "Sot asht e martë.",
    introducedWeek: 4,
    frequency: "high",
  },
  {
    ghegWord: "nesër",
    englishMeaning: "tomorrow",
    partOfSpeech: "adverb",
    exampleSentence: "Nesër kam provim.",
    introducedWeek: 4,
    frequency: "high",
  },
  // ─── Week 5: Evening / Home routine ──────────────────────────────────────
  {
    ghegWord: "darkë",
    englishMeaning: "dinner / supper",
    partOfSpeech: "noun",
    exampleSentence: "Darkën e hamë gjithë bashkë.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "televizor",
    englishMeaning: "television / TV",
    partOfSpeech: "noun",
    exampleSentence: "Shohim filma në televizor pas darkës.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "gjumë",
    englishMeaning: "sleep",
    partOfSpeech: "noun",
    exampleSentence: "Kam nevojë për gjumë, jam i lodhun.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "fle",
    englishMeaning: "sleeps / to sleep",
    partOfSpeech: "verb",
    exampleSentence: "Fëmija fle në orën nëntë mbrëmë.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "lexon",
    englishMeaning: "reads / to read",
    partOfSpeech: "verb",
    exampleSentence: "Ajo lexon libra çdo natë para gjumit.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "dëgjon",
    englishMeaning: "listens / to listen",
    partOfSpeech: "verb",
    exampleSentence: "Ai dëgjon muzikë kur studion.",
    introducedWeek: 5,
    frequency: "high",
  },
  // ─── Week 5: Emotions ─────────────────────────────────────────────────────
  {
    ghegWord: "i lumtur",
    englishMeaning: "happy (masculine)",
    partOfSpeech: "adjective",
    exampleSentence: "Jam i lumtur kur jam me familjen time.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "i lodhun",
    englishMeaning: "tired (masculine) — Gheg form",
    partOfSpeech: "adjective",
    exampleSentence: "Jam i lodhun pas punës.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "i trishtun",
    englishMeaning: "sad (masculine) — Gheg form",
    partOfSpeech: "adjective",
    exampleSentence: "Asht i trishtun sot, nuk di pse.",
    introducedWeek: 5,
    frequency: "medium",
  },
  {
    ghegWord: "i shqetësun",
    englishMeaning: "worried / anxious (masculine) — Gheg form",
    partOfSpeech: "adjective",
    exampleSentence: "Asht i shqetësun për provimin nesër.",
    introducedWeek: 5,
    frequency: "medium",
  },
  {
    ghegWord: "i kënaqun",
    englishMeaning: "satisfied / content (masculine) — Gheg form",
    partOfSpeech: "adjective",
    exampleSentence: "Jam i kënaqun me rezultatin e sotëm.",
    introducedWeek: 5,
    frequency: "medium",
  },
  // ─── Week 5: Additional common verbs ─────────────────────────────────────
  {
    ghegWord: "mëson",
    englishMeaning: "learns / studies / to learn",
    partOfSpeech: "verb",
    exampleSentence: "Mëson gjuhën angleze në shkollë.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "ndihmon",
    englishMeaning: "helps / to help",
    partOfSpeech: "verb",
    exampleSentence: "Vëllai ndihmon nënën me punët e shtëpisë.",
    introducedWeek: 5,
    frequency: "high",
  },
  {
    ghegWord: "pret",
    englishMeaning: "waits / to wait",
    partOfSpeech: "verb",
    exampleSentence: "Pret autobusin çdo mëngjes.",
    introducedWeek: 5,
    frequency: "medium",
  },
  {
    ghegWord: "gatuen",
    englishMeaning: "cooks / to cook — Gheg form",
    partOfSpeech: "verb",
    exampleSentence: "Nëna gatuen gjellë të shijshme.",
    introducedWeek: 5,
    frequency: "high",
  },
];
